site_name: test
site_url: https://poiqazwsx.github.io/mkdocs-test
theme:
  name: material
  palette:
    scheme: slate
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: ./assets/favicon.png
  icon:
    logo: logo
